#!/bin/bash
echo "=== 更新 EC2 后端代码和重启服务 ==="
echo ""
echo "步骤 1: 上传修改后的 main.py"
echo "  在本地运行: scp -i your-key.pem /Users/cai/shopping/backend/main.py ec2-user@13.159.19.120:/home/ec2-user/shopping/backend/"
echo ""
echo "步骤 2: SSH 到 EC2"
echo "  ssh -i your-key.pem ec2-user@13.159.19.120"
echo ""
echo "步骤 3: 在 EC2 上重启服务"
echo "  sudo systemctl restart campus_trade"
echo "  sudo systemctl status campus_trade"
echo ""
echo "步骤 4: 查看后端日志（如果有错误）"
echo "  sudo journalctl -u campus_trade -f"
